version: '1.0'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - /app/node_modules
    restart: on-failure
    env_file:
      - .env